(()=>{'use strict';
const C=window.COURSE, KEY='machine-learning-workbench-v1',DAY=86400000,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({version:1,seen:{},attempts:[],notes:{},diagnosis:null,exam:null,history:[]});let S=fresh(),persistent=true;try{S=validate(JSON.parse(localStorage.getItem(KEY)))||fresh()}catch{};
function validate(x){
if(!x||x.version!==1||!Array.isArray(x.attempts)||!Array.isArray(x.history)||!x.seen||typeof x.seen!=='object'||!x.notes||typeof x.notes!=='object')return null;
if(x.attempts.some(a=>!a||!C.questions.some(q=>q.id===a.id)||typeof a.ok!=='boolean'||!Number.isFinite(a.time)))return null;
const s=fresh();s.seen=Object.fromEntries(Object.entries(x.seen).filter(([k,v])=>C.lessons.some(l=>l.id===k)&&Number.isFinite(v)));s.notes=Object.fromEntries(Object.entries(x.notes).filter(([k,v])=>typeof v==='string'&&v.length<=20000&&k!=='__proto__'));
s.attempts=x.attempts.slice(-5000).map(a=>({id:a.id,ok:a.ok,time:a.time,hint:!!a.hint,review:!!a.review,value:String(a.value||'').slice(0,100)}));
if(x.diagnosis&&Number.isFinite(x.diagnosis.time)&&Array.isArray(x.diagnosis.weak))s.diagnosis={time:x.diagnosis.time,weak:x.diagnosis.weak.filter(id=>C.lessons.some(l=>l.id===id))};
s.history=x.history.filter(h=>h&&['A','B'].includes(h.version)&&Number.isFinite(h.time)&&Number.isFinite(h.score)&&h.score>=0&&h.score<=100).slice(0,30).map(h=>({version:h.version,time:h.time,score:h.score,...(Number.isFinite(h.manual)&&h.manual>=0&&h.manual<=14?{manual:h.manual}:{})}));
if(x.exam){let e=x.exam;if(!['A','B'].includes(e.version)||!Number.isFinite(e.start)||!Number.isFinite(e.end)||e.end<=e.start||!e.answers||typeof e.answers!=='object'||typeof e.proof!=='string'||typeof e.submitted!=='boolean')return null;
s.exam={version:e.version,start:e.start,end:e.end,answers:Object.fromEntries(Object.entries(e.answers).filter(([k,v])=>/^e\d+[abcd]?$/.test(k)&&typeof v==='string').map(([k,v])=>[k,v.slice(0,100)])),proof:e.proof.slice(0,20000),submitted:e.submitted};
if(e.submitted){if(!Number.isFinite(e.score)||!Number.isFinite(e.submittedAt))return null;Object.assign(s.exam,{score:Math.max(0,Math.min(100,e.score)),submittedAt:e.submittedAt});if(Array.isArray(e.manualChecks)){s.exam.manualChecks=[0,1,2,3].filter(i=>e.manualChecks.includes(i));s.exam.manual=s.exam.manualChecks.reduce((a,i)=>a+[4,4,4,2][i],0)}}
}return s}

function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{persistent=false;toast('无法保存到浏览器，请导出学习备份。')}}function toast(t){$('#toast').textContent=t;setTimeout(()=>$('#toast').textContent='',4200)}
const lesson=id=>C.lessons.find(l=>l.id===id),qby=id=>C.questions.find(q=>q.id===id),link=(id,t)=>`<a class="btn secondary small-btn" href="#learn/${id}">${esc(t||lesson(id).title)}</a>`;
function status(l){const a=C.questions.filter(q=>q.lesson===l.id).map(q=>S.attempts.filter(a=>a.id===q.id).at(-1)).filter(Boolean),good=a.filter(a=>a.ok&&!a.hint);return good.length>=2&&good.some(a=>qby(a.id).transfer)?(good.some(a=>a.review)?'复习通过':'练习通过'):S.seen[l.id]?'正在学习':'未开始'}
function next(){const weak=S.diagnosis?.weak||[];return C.lessons.find(l=>weak.includes(l.id)&&!status(l).includes('通过'))||C.lessons.find(l=>!status(l).includes('通过'))||C.lessons[0]}
function due(){return C.questions.filter(q=>{let a=S.attempts.filter(a=>a.id===q.id).at(-1);return a&&(!a.ok||a.time+(a.review?3:1)*DAY<=Date.now())})}
const nav=[['today','◷','今天学什么'],['path','▦','学习路线 · 12 章'],['labs','⌁','互动实验'],['review','↻','错题复习'],['exam','▤','模拟测验'],['resources','☷','资源与备份']];
function shell(body,route){$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#today"><span class="brand-icon">∑</span>机器学习练习室</a><div class="brand-small">机器学习 · 从零开始 · 每天 30 分钟</div><nav>${nav.map(([id,i,t])=>`<a class="nav-link ${route===id?'active':''}" href="#${id}"><span class="nav-symbol">${i}</span>${t}</a>`).join('')}</nav><div class="sidebar-foot">每天 30 分钟<br>先补基础，再跟课程。</div></aside><div class="main-wrap"><header class="topbar"><span>机器学习 / 学习工作台</span><span class="small">${persistent?'进度仅存当前浏览器':'保存不可用，请及时导出'}</span></header><main id="main" class="content" tabindex="-1">${body}</main></div></div><nav class="mobile-menu" aria-label="主要导航">${nav.map(([id,i,t])=>`<a class="${route===id?'active':''}" href="#${id}"><span class="nav-symbol">${i}</span>${({today:'今天',path:'路线',labs:'实验',review:'复习',exam:'测验',resources:'资源'})[id]}</a>`).join('')}</nav>`}
const heading=(a,b)=>`<div class="page-heading"><div><div class="eyebrow">机器学习练习室 / LEARN BY DOING</div><h1>${a}</h1><p class="muted">${b}</p></div></div>`;
function today(){let l=next(),n=C.lessons.filter(l=>status(l).includes('通过')).length;shell(heading('今天，先弄懂一小步','30 分钟 · 先补基础再跟课 · 不用一次读完整章')+`<section class="card soft section-space"><h2>第一次接触编程？先看 Python 小课</h2><p>从 print(2 + 3) 开始，逐行看输入和输出。理论可以同时学，不要求先学完一整本编程书。</p><a class="btn" href="#rstart">进入 Python 零基础 →</a></section><div class="grid grid-main section-space"><section class="lesson-hero"><div class="hero-inner"><span class="tag">${l.group}</span><h2 class="lesson-title">${l.title}</h2><p>${l.simple}</p><ol class="step-list"><li><span class="step-no">5′</span><div><strong>先回忆</strong><p>有到期题就复习；初次学习先做基础诊断。</p></div></li><li><span class="step-no">15′</span><div><strong>理解一个知识点</strong><p>${l.method}</p></div></li><li><span class="step-no">10′</span><div><strong>独立做题，再说理由</strong><p>先答再看提示。错了就回到缺失的那一步。</p></div></li></ol></div><div class="hero-bottom"><a class="btn" href="#learn/${l.id}">开始今天的学习 →</a><a href="#diagnostic">${S.diagnosis?'重做基础诊断':'先做 8 题基础诊断'}</a></div></section><aside class="grid"><section class="card"><h2>你的学习证据</h2><div class="stat-row"><div class="stat"><strong>${n} / ${C.lessons.length}</strong><span>全部学习单元通过</span></div><div class="stat"><strong>${due().length}</strong><span>待纠错 / 到期题</span></div></div><div class="progress-track"><div class="progress-fill" style="width:${n/C.lessons.length*100}%"></div></div><p class="small muted">每节至少 2 道独立答对，且包含迁移题，才算练习通过。读过不等于掌握。</p><a href="#review">打开复习队列 →</a></section><section class="card soft"><h3>卡住不是只能重读</h3><p>看不懂符号：展开成数字。<br>会算但不懂：拖动图形做预测。<br>推导断了：逐步补齐依据。<br>代码看不懂：追踪每行输入输出。</p></section></aside></div><section class="card section-space"><h2>整门课都在这里</h2><p><a class="btn secondary" href="#path">打开机器学习 12 章路线 →</a></p><p>${C.scope}</p><p class="small muted">${C.sourceNote}</p></section>`,'today')}
const chapterLessons=ch=>[...new Set([...ch.sections.flatMap(s=>s.lessons),...(ch.extras||[])])];
function chapterStats(ch){let ids=chapterLessons(ch);return {total:ids.length,passed:ids.filter(id=>status(lesson(id)).includes('通过')).length}}
function path(){shell(heading('学习路线 · 12 章','从问题、数据与代码起步。选择章节进入讲解、例题、练习和应用任务。')+`<section class="card"><div class="actions"><a class="btn" href="#rstart">Python 从零入门（5 节）</a><a class="btn secondary" href="#foundations">按需补数学</a><a class="btn secondary" href="#coursecheck">全课程 24 题自测</a><a class="btn secondary" href="#projects">三个最小项目</a></div><p class="small muted section-space">这是通用机器学习自学路线，并非特定学校考纲。先学当前需要的基础；理论理解与项目实践交替进行。</p><label class="field">查找知识点<input id="course-search" type="search" placeholder="例如：决策树、kNN、PCA、Python"></label><div id="search-results"></div></section><div class="grid grid-2 section-space">${C.chapters.map(ch=>{let st=chapterStats(ch);return `<section class="card chapter-card"><div class="actions"><span class="tag">第 ${ch.id} 章</span>${ch.tentative?'<span class="tag amber">大纲暂定</span>':''}</div><h2>${ch.title}</h2><p class="small">${ch.objective}</p><p class="small muted">${ch.sections.length} 小节 · ${st.passed}/${st.total} 关联单元练习通过</p><div class="progress-track"><div class="progress-fill" style="width:${st.passed/st.total*100}%"></div></div><p class="section-space"><a class="btn secondary" href="#chapter/${ch.id}">进入这一章 →</a></p></section>`}).join('')}</div>`,'path');$('#course-search').oninput=e=>{let v=e.target.value.trim().toLowerCase();$('#search-results').innerHTML=v?C.lessons.filter(l=>(l.title+' '+l.formula+' '+l.intro.join(' ')).toLowerCase().includes(v)).map(l=>`<p>${link(l.id)} <span class="small muted">${l.group}</span></p>`).join('')||'<p>未找到。可尝试中文名称或查看章目录。</p>':''}}
function rStart(){shell(heading('Python 从第一行开始','5 节入门小课。手机先预测和追踪，电脑再亲手运行。')+`<section class="card soft"><h2>今天只弄懂一行</h2><pre><code>print(2 + 3)</code></pre><p>输出是 5。print 表示把结果显示出来。下一步尝试改一个数，先猜结果。</p>${link('pyfirst','开始第 1 节')}</section><div class="route-list section-space">${C.rpath.map(id=>`<a class="route-item" href="#learn/${id}"><div><strong>${lesson(id).title}</strong><p>讲解 → 逐行追踪 → 独立练习</p></div><span class="tag">${status(lesson(id))}</span></a>`).join('')}</div><section class="card section-space"><h2>什么时候用电脑？</h2><p>前 3 节可先用手机演示理解。电脑上可安装 <a href="https://www.python.org/downloads/" target="_blank" rel="noopener">Python</a>，用自带 IDLE 或熟悉的编辑器运行 .py 文件。NumPy 和 scikit-learn 到相关实验时再安装。</p><p><a href="Python第一天.py" download>下载不依赖第三方包的第一次练习</a></p><p class="small muted">页面演示是固定示例，不运行任意 Python，也不会安装软件。</p></section>`,'path')}
function rTrace(id){let l=lesson(id);if(!l?.rtrace){rStart();return}let step=0;shell(heading(l.title,'固定示例的逐行教学演示，不执行任意 Python 代码。先预测，再打开解释。')+`<div class="grid grid-main"><section class="card"><div id="r-trace-content" aria-live="polite"></div></section><aside class="card"><h2>先猜这一行的结果</h2><label class="field">我的预测<textarea id="r-guess" placeholder="会得到一个数、一组数、一张表，还是只保存对象？">${esc(S.notes['rguess-'+id]||'')}</textarea></label><div class="actions"><button id="r-next" class="btn">看这一行的解释</button><button id="r-reset" class="btn secondary">从头演示</button></div><p class="small muted section-space">看过演示不自动算练习通过。去做题，再在电脑上改一个输入验证。</p>${link(id,'回到这一节')}<p class="section-space"><a href="#learn/${id}/practice">独立做 3 道题 →</a></p></aside></div>`,'path');function draw(){$('#r-trace-content').innerHTML=l.rtrace.map(([code,out,why],i)=>`<section class="reading-task"><strong>第 ${i+1} 行</strong><pre><code>${esc(code)}</code></pre>${i<step?`<div class="notice"><strong>结果 / 状态</strong><pre>${esc(out)}</pre><p>${esc(why)}</p></div>`:'<p class="muted">先猜会发生什么，再继续。</p>'}</section>`).join('');$('#r-next').disabled=step>=l.rtrace.length;$('#r-next').textContent=step>=l.rtrace.length?'已看完，去独立练习':'解释第 '+(step+1)+' 行'}$('#r-next').onclick=()=>{step++;draw()};$('#r-reset').onclick=()=>{step=0;draw()};$('#r-guess').oninput=e=>{S.notes['rguess-'+id]=e.target.value;save()};draw()}
function foundations(){shell(heading('基础补课','先学当前章节需要的基础，不要求把所有数学书读完。')+`<div class="route-list">${C.lessons.filter(l=>l.group==='基础补课'||['mean','spread','prob','matrix','derivative'].includes(l.id)).map(l=>`<a class="route-item" href="#learn/${l.id}"><div><strong>${l.title}</strong><p class="small muted">${l.method}</p></div><span class="tag">${status(l)}</span></a>`).join('')}</div>`,'path')}
function chapter(id){let ch=C.chapters.find(c=>c.id===Number(id));if(!ch){path();return}let ids=chapterLessons(ch),rs=C.resources.filter(r=>r.topics.some(t=>ids.includes(t)));shell(heading(`第 ${ch.id} 章 · ${ch.title}`,ch.objective)+`<div class="actions"><a href="#path">← 全课程目录</a><a class="btn secondary" href="#chaptercheck/${ch.id}">本章练习与查漏</a><a class="btn secondary" href="#resources/chapter-${ch.id}">本章公开资料（${rs.length}）</a></div><p class="notice section-space">${ch.basis}${ch.tentative?' 第十四章是否实施与具体要求，待教师确认。':''}</p><section class="card"><h2>先理解，再应试</h2><div class="grid grid-2"><div><h3>真正会用</h3><p>能说明输入、输出、目标、假设和一个失败情形。用一个新例子检验，不以看完作为完成。</p></div><div><h3>闭卷练习</h3><p>不看答案列出条件与公式，手算本章例题。错在符号就补先修，错在条件就比较反例。本站不把后续主题标成已确认考点。</p></div></div></section>${ch.sections.map(sec=>`<section class="card section-space"><span class="tag">${ch.id}.${sec.number}</span><h2>${sec.title}</h2><div class="grid">${sec.lessons.map(id=>{let l=lesson(id);return `<div class="outline-row"><div><strong>${l.title}</strong><p class="small muted">${l.method}</p><span class="tag gray">${status(l)}</span></div>${link(id,'打开学习')}</div>`}).join('')}</div></section>`).join('')}${ch.extras?.length?`<section class="card section-space"><h2>章标题延伸：非线性回归</h2>${ch.extras.map(id=>link(id)).join('')}</section>`:''}<p class="section-space"><a class="btn secondary" href="#projects">进入三个最小项目 →</a></p><section class="card section-space"><h2>把知识用一次</h2><p>${ch.project}</p><label class="field">我的实验或思考记录<textarea id="chapter-note" rows="6" placeholder="问题 → 方法 → 结果 → 哪些结论不能推出">${esc(S.notes['chapter-'+ch.id]||'')}</textarea></label><p class="small muted">自动保存。这是应用记录，不自动冒充客观得分。</p>${ch.id<C.chapters.length?`<a class="btn secondary" href="#chapter/${ch.id+1}">查看下一章</a>`:''}</section>`,'path');$('#chapter-note').oninput=e=>{S.notes['chapter-'+ch.id]=e.target.value;save()}}
function chapterCheck(id){let ch=C.chapters.find(c=>c.id===Number(id));if(!ch){path();return}let qs=chapterLessons(ch).flatMap(id=>C.questions.filter(q=>q.lesson===id));shell(heading(`第 ${ch.id} 章 · 查漏练习`,'复用单元题库，逐题反馈，不是独立官方试卷。先不看笔记；答错后直接回到对应单元。')+`<p><a href="#chapter/${ch.id}">← 返回本章</a></p><section class="card">${qs.map(q=>quiz(q)).join('')}</section>`,'exam');bindQuiz()}
function courseCheck(){const qs=C.chapters.flatMap(ch=>{let ids=chapterLessons(ch),a=C.questions.filter(q=>ids.includes(q.lesson));return [a.find(q=>q.type==='number'),a.findLast(q=>q.transfer)].filter(Boolean).map(q=>({ch,q}))});shell(heading('全课程 24 题自测','每章一个计算检查、一个迁移检查。来自课程练习库；用于定位薄弱章，不代表考试命题或完整掌握。')+qs.map(({ch,q})=>`<section class="card section-space"><h2>第 ${ch.id} 章 · ${ch.title}</h2>${quiz(q)}</section>`).join(''),'exam');bindQuiz()}

function quiz(q,review=false){return `<form class="question" data-q="${q.id}" data-review="${review}"><fieldset><legend>${q.transfer?'【迁移】':''}${esc(q.prompt)}</legend>${q.type==='choice'?q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" required> ${esc(o)}</label>`).join(''):`<label class="field">你的计算结果<input name="answer" inputmode="decimal" placeholder="可填小数或分数，如 1/9" required autocomplete="off"></label>`}</fieldset><details class="hint"><summary>需要一点提示</summary><p>${esc(q.hint)}</p></details><button class="btn small-btn" type="submit">检查答案</button><div class="feedback" aria-live="polite"></div></form>`}
function numeric(v){v=String(v).trim();if(!v)return NaN;if(/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(v))return Number(v);if(/^[+-]?\d+(?:\.\d+)?\s*\/\s*[+-]?\d+(?:\.\d+)?$/.test(v)){let[a,b]=v.split('/').map(Number);return b?a/b:NaN}return NaN}
function bindQuiz(){document.querySelectorAll('form[data-q]').forEach(f=>{let hinted=false;f.querySelector('details').ontoggle=e=>{if(e.target.open)hinted=true};f.onsubmit=e=>{e.preventDefault();let q=qby(f.dataset.q),v=new FormData(f).get('answer'),n=numeric(v),ok=q.type==='choice'?String(q.answer)===v:Number.isFinite(n)&&Math.abs(n-q.answer)<=(q.tolerance||.005);if(v===null||!String(v).trim()){toast('请先作答');return}let previous=S.attempts.filter(a=>a.id===q.id).at(-1),review=f.dataset.review==='true'&&previous&&Date.now()-previous.time>=DAY;S.attempts.push({id:q.id,ok,time:Date.now(),hint:hinted,review:!!review,value:String(v)});save();f.querySelector('.feedback').innerHTML=`<strong>${ok?'答对了':'再检查一下'}</strong><p>${esc(q.explain)}</p>${hinted?'<p class="small">本次使用提示，记录为辅助练习。请之后独立复习。</p>':''}${!ok?`<p>本题重点：${esc(q.kind)}。${link(q.lesson,'回到这节的讲解')}</p>`:''}`;f.querySelector('.feedback').classList.toggle('wrong',!ok);f.querySelector('button').disabled=true;f.querySelectorAll('input').forEach(i=>i.disabled=true)}})}
function learn(id,tab='understand'){const l=lesson(id);if(!l){location.hash='path';return}S.seen[id]=S.seen[id]||Date.now();save();let body='';if(tab==='understand')body=`<h2>先说人话</h2>${l.intro.map(p=>`<p>${p}</p>`).join('')}<details><summary>还是抽象？换个小例子</summary><p>${l.simple}</p></details><div class="math">${l.formula}</div><h3>把符号逐个拆开</h3><div class="formula-parts">${Object.entries(l.terms).map(([k,v])=>`<details><summary>${esc(k)}</summary><p>${esc(v)}</p></details>`).join('')}</div><p class="notice">学习方法：${l.why}</p><a class="btn" href="#learn/${id}/worked">跟着做一个例子 →</a>`;
if(tab==='worked')body=`<h2>先尝试，再打开下一步</h2><p>${l.example}</p><label class="field">先写下你想从哪一步开始<textarea id="scratch" placeholder="不要求写对，先留下你的思路。">${esc(S.notes[id+'-scratch']||'')}</textarea></label>${l.steps.map(([h,t],i)=>`<details><summary>第 ${i+1} 步 · ${h}</summary><p>${t}</p></details>`).join('')}<p class="notice warn">容易踩的坑：${l.trap}</p><a class="btn" href="#learn/${id}/practice">不看答案，自己试一次 →</a>`;
if(tab==='practice')body=`<h2>独立练习</h2><p class="small muted">先尝试，不会再用提示。答完会解释理由；本节第 3 题检验迁移。</p>${l.questions.map(id=>quiz(qby(id))).join('')}`;
if(tab==='resources')body=lessonReading(l);
if(tab==='recall')body=`<h2>合上讲义，你能讲清楚吗？</h2><ul>${l.recall.map(t=>`<li>${t}</li>`).join('')}</ul><label class="field">用自己的话解释，并写下仍不懂的一处<textarea id="recall" rows="6" placeholder="这是什么 → 为什么这样做 → 什么时候不能用">${esc(S.notes[id]||'')}</textarea></label><p class="small muted">文字自动保存在本机；自述不自动计入掌握率。</p><a class="btn" href="#today">回到今日安排</a>`;
shell(heading(l.title,`${l.group} · ${l.method}`)+`<div class="tabs">${[['understand','① 看懂'],['worked','② 跟着做'],['practice','③ 独立做'],['recall','④ 讲出来'],['resources','⑤ 继续学']].map(([t,n])=>`<a class="tab ${tab===t?'active':''}" href="#learn/${id}/${t}">${n}</a>`).join('')}</div><div class="grid grid-main"><article class="card lesson-body">${body}</article><aside class="grid"><section class="card"><h3>我卡在哪里？</h3><p class="small">符号看不懂，先回到基础；运算卡住，展开具体数字再试。</p><div class="actions">${(l.pre.length?l.pre:['mean']).map(i=>link(i)).join('')}${link('pyfirst','Python 看不懂')}</div>${l.rtrace?`<p><a class="btn" href="#rtrace/${l.id}">逐行演示 · 先猜再看</a></p>`:''}${l.lab?`<a class="btn section-space" href="#labs/${l.lab}">用互动实验理解</a>`:''}</section><section class="card soft"><h3>本节对应</h3><p class="small">${l.source}</p>${l.sourceUrl?`<p><a target="_blank" rel="noopener" href="${l.sourceUrl}">核对原理来源 ↗</a></p>`:''}<div class="actions">${(l.chapters||[]).map(n=>`<a href="#chapter/${n}">第 ${n} 章</a>`).join('')}</div><span class="tag">${status(l)}</span><p class="small">先读条件，再代公式。练习通过后，隔天再检验。</p></section></aside></div>`,'path');bindQuiz();if($('#recall'))$('#recall').oninput=e=>{S.notes[id]=e.target.value;save()};if($('#scratch'))$('#scratch').oninput=e=>{S.notes[id+'-scratch']=e.target.value;save()}}
function diagnostic(){shell(heading('8 题基础诊断','约 5 分钟。不会就选“暂时不会”，这比猜对更有用。')+`<form id="diagnostic" class="card">${C.diagnostic.map((q,k)=>`<fieldset class="question"><legend>${k+1}. ${q.prompt}</legend>${q.options.map((t,i)=>`<label class="option"><input type="radio" name="${q.id}" value="${i}" required> ${t}</label>`).join('')}</fieldset>`).join('')}<button class="btn">生成补课建议</button></form>`,'today');$('#diagnostic').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),weak=C.diagnostic.filter(q=>String(q.answer)!==f.get(q.id)).map(q=>q.lesson);S.diagnosis={time:Date.now(),weak};save();shell(heading('从这些缺口开始','这只是每个主题一道题的初筛，不是掌握证明。')+`<section class="card"><p>本次 ${8-weak.length}/8 道正确。${weak.length?'建议先补下面的基础，再进入课程。':'可以从第一讲开始，但仍用独立练习验证。'}</p>${C.diagnostic.map(q=>`<p><strong>${weak.includes(q.lesson)?'需补课':'初筛通过'} · ${lesson(q.lesson).title}</strong><br>${q.explain}</p>${weak.includes(q.lesson)?link(q.lesson):''}`).join('')}<p>${link(weak[0]||'model','开始推荐单元')}</p></section>`,'today')}}
function review(){let qs=due();shell(heading('错题与间隔复习','答错立即纠正；独立答对后隔 1 天复习，通过后隔 3 天再测。同一天重做不算间隔复习。')+`<section class="card"><h2>${qs.length?`${qs.length} 道题等待你`:'目前没有到期题'}</h2><p class="muted">${qs.length?'先看题自己回答，再看解释。题目可能重复，因此“复习通过”只表示这组练习的表现。':'先完成一个单元的练习。之后你会在这里看到错题和到期复习。'}</p>${qs.map(q=>quiz(q,true)).join('')}${!qs.length?link(next().id,'去学今天的一节'):''}</section>`,'review');bindQuiz()}
function lessonReading(l){let rs=C.resources.filter(r=>r.topics.includes(l.id));return `<h2>把这一节学扎实</h2><p>每天最多选一个补充任务。先完成本页例题，再打开外部材料。看完要回到独立练习，不能用收藏代替学习。</p>${l.code?`<h3>最小 Python 实验</h3><pre><code>${esc(l.code)}</code></pre><p class="small muted">在 Python 环境中运行；本页不执行代码。先预测输出，再改一个输入并解释变化。</p>`:''}${rs.length?rs.map(r=>`<section class="reading-task"><span class="tag">${r.type}</span><h3>${r.name}</h3><p>${r.task}</p><p><strong>学会的证据：</strong>${r.finish}</p><p class="small muted">${r.note}</p><div class="actions"><a href="${r.url}" target="_blank" rel="noopener">读指定资料 ↗</a><a href="${r.repo}" target="_blank" rel="noopener">看代码来源 ↗</a></div></section>`).join(''):`<p>先完成本节例题与迁移题。${l.sourceUrl?`<a href="${l.sourceUrl}" target="_blank" rel="noopener">再核对原始方法说明 ↗</a>`:'<a href="#resources">按需要选择基础补充资源</a>'}</p>`}<h3>留下一个可检查的结果</h3><p>写出：我修改了什么 → 结果怎样变 → 哪条原理解释这个变化。把记录保存在“讲出来”页。</p>`}
function resources(filter=''){const selected=filter.startsWith('chapter-')?C.resources.filter(r=>r.topics.some(t=>chapterLessons(C.chapters[Number(filter.slice(8))-1]||C.chapters[0]).includes(t))):filter?C.resources.filter(r=>r.topics.includes(filter)):C.resources;shell(heading('公开资料 · 带着问题去学','先用内置讲解；只在具体卡点上补充，不需要同时学完这些书。')+`<p><a href="#resources">全部 ${C.resources.length} 项</a> · ${filter?'已按关联章节筛选':'中文入门 → 动手复现 → 原理推导 → 研究阅读'}</p><div class="grid grid-2">${selected.map(r=>`<section class="card"><span class="tag">${r.type}</span><h2>${r.name}</h2><p><strong>什么时候看：</strong>${r.when}</p><p><strong>只做这件事：</strong>${r.task}</p><p><strong>完成标准：</strong>${r.finish}</p><p class="small muted">${r.note}<br>语言：${r.language||'中文/英文'} · 链接核对：${r.checked||'2026-09-26'}</p><div class="actions"><a target="_blank" rel="noopener" href="${r.url}">打开资源 ↗</a><a target="_blank" rel="noopener" href="${r.repo}">GitHub 仓库 ↗</a></div></section>`).join('')}</div><section class="card section-space"><h2>学习数据备份</h2><p>进度、笔记和测验仅保存在当前设备的浏览器。换手机或清理浏览器前请导出；GitHub 不会同步你的学习记录。</p><button class="btn" id="export">导出 JSON 备份</button><label class="field section-space">从备份恢复（将替换当前记录）<input id="import" type="file" accept="application/json,.json"></label><p class="small muted">${C.referenceNote}</p><a href="https://github.com/sallowayma-git/IELTS-practice" target="_blank" rel="noopener">流程参考：IELTS-practice</a></section>`,'resources');$('#export').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.href=u;a.download='机器学习练习室-学习备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('#import').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>2e6)throw Error();const s=validate(JSON.parse(await f.text()));if(!s)throw Error();if(!confirm('恢复备份会替换本机当前记录。已导出需要保留的记录吗？'))return;S=s;save();toast('备份恢复成功')}catch{toast('备份无效或超过 2 MB，当前记录未变更。')}}}
const labsList={ols:'回归线与误差',overfit:'复杂度与泛化',shrink:'Ridge 与 Lasso',pcaview:'PCA 投影',threshold:'分类阈值',attention:'注意力',rankview:'LoRA 参数',neighbors:'最近邻预测',clusters:'聚类分组',splitter:'树的切分'};
const avg=a=>a.reduce((s,v)=>s+v,0)/a.length,sum=a=>a.reduce((s,v)=>s+v,0),fmt=n=>Number.isFinite(n)?Number(n.toFixed(4)).toString():'不可计算';
function slider(id,label,min,max,value,step=1){return `<label class="range-field">${label}：<output id="${id}-v">${value}</output><input type="range" id="${id}" min="${min}" max="${max}" value="${value}" step="${step}"></label>`}
function chart(points,line,extra=[]){let all=[...points,...line,...extra],xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);let xx=x=>45+(x-xmin)/(xmax-xmin||1)*505,yy=y=>250-(y-ymin)/(ymax-ymin||1)*220;return `<svg viewBox="0 0 580 290" role="img" aria-label="散点与拟合曲线；数值和解释见下方"><path d="M45 20V250H555" stroke="#94a3b8" fill="none"/><text x="45" y="276" font-size="12">x = ${fmt(xmin)}</text><text x="487" y="276" font-size="12">${fmt(xmax)}</text><text x="3" y="25" font-size="11">${fmt(ymax)}</text><text x="3" y="248" font-size="11">${fmt(ymin)}</text>${line.length?`<polyline points="${line.map(p=>`${xx(p[0])},${yy(p[1])}`).join(' ')}" fill="none" stroke="#275bd7" stroke-width="3"/>`:''}${points.map(p=>`<circle cx="${xx(p[0])}" cy="${yy(p[1])}" r="5" fill="#153054"/>`).join('')}${extra.map(p=>`<circle cx="${xx(p[0])}" cy="${yy(p[1])}" r="3" fill="#d18428"/>`).join('')}</svg>`}
function solve(a,b){a=a.map((r,i)=>[...r,b[i]]);let n=b.length;for(let i=0;i<n;i++){let k=i;for(let j=i+1;j<n;j++)if(Math.abs(a[j][i])>Math.abs(a[k][i]))k=j;if(Math.abs(a[k][i])<1e-12)return null;[a[i],a[k]]=[a[k],a[i]];let d=a[i][i];for(let t=i;t<=n;t++)a[i][t]/=d;for(let j=0;j<n;j++)if(i!==j){d=a[j][i];for(let t=i;t<=n;t++)a[j][t]-=d*a[i][t]}}return a.map(r=>r[n])}
function labs(id='ols'){if(['neighbors','clusters','splitter'].includes(id)){mlLab(id);return}if(['shrink','pcaview','threshold','attention','rankview'].includes(id)){advancedLab(id);return}if(!labsList[id])id='ols';let controls='',intro='',lessonId='ols';if(id==='mean'){controls=slider('a','第一个数',0,12,2)+slider('b','第二个数',0,12,4)+slider('c','第三个数',0,12,6);intro='先预测：把最大值继续调大，均值与平方和会怎样变？';lessonId='spread'}
if(id==='ols'){controls=slider('a','截距 a',-3,6,0,.1)+slider('b','斜率 b',-1,4,1,.05)+'<button class="btn secondary" id="best">对照最小二乘解</button>';intro='先自己拖动，让点到直线的竖直误差平方和最小，再对照最优解。'}
if(id==='sampling'){controls=slider('n','每次样本量 n',2,100,10)+slider('sigma','个体标准差 σ',1,10,4)+ '<button class="btn secondary" id="resample">重新抽取 100 组样本</button>';intro='总体均值固定为 5。先预测：增大 n 后，样本均值会更集中还是更分散？';lessonId='se'}
if(id==='matrix'){controls=slider('x','样本特征 x',-5,5,2)+slider('a','截距 β₀',-5,5,1)+slider('b','斜率 β₁',-5,5,3);intro='一行样本乘一列系数，得到一个预测值。先口算，再拖动核对。';lessonId='matrix'}
if(id==='test'){controls=slider('b','估计系数 b',-3,3,1,.05)+slider('se','标准误 SE',.1,2,.5,.05);intro='固定自由度 18，双侧 5% 临界值 2.1009，检验 H₀: β=0。先预测增大 SE 会怎样。';lessonId='test'}
if(id==='prediction'){controls=slider('x','新位置 x₀',-5,5,0,.1);intro='固定 n=25，x̄=0，SXX=50，残差标准差 s=2，拟合均值 3+x₀。自由度23，t临界值2.0687。';lessonId='prediction'}
if(id==='collinear'){controls=slider('eps','两列的区别 ε',0,2,.5,.01)+slider('perturb','第一个 y 的扰动',-.3,.3,0,.01);intro='X₂=X₁+εz。先把 ε 调小，再微调一个 y，观察系数是否大幅变化。';lessonId='collinear'}
if(id==='overfit'){controls=slider('degree','多项式次数',1,8,1);intro='固定 12 个训练点和 40 个留出点，拟合带噪声的曲线。改变复杂度，比较两种误差；这一次模拟不保证每级验证误差都变大。';lessonId='overfit'}
if(id==='code'){controls='<button class="btn" id="nextline">执行下一行（教学追踪）</button><button class="btn secondary" id="resetcode">从头开始</button>';intro='这是预先校验的逐行教学演示，不是在线 R 解释器。每一行先猜输出，再继续。';lessonId='rcode'}
shell(heading(labsList[id],intro)+`<div class="pill-row">${Object.entries(labsList).map(([k,v])=>`<a class="pill ${k===id?'active':''}" href="#labs/${k}">${v}</a>`).join('')}</div><div class="grid grid-main section-space"><section class="card"><div id="labresult" aria-live="polite"></div></section><aside class="card"><h2>动手改变一个量</h2>${controls}<div class="divider"></div><label class="field">我的预测和观察<textarea id="labnote" placeholder="我原以为……改变后发现……原因可能是……">${esc(S.notes['lab-'+id]||'')}</textarea></label>${link(lessonId,'回到对应知识点')}</aside></div>`,'labs');let seed=137,line=0;function rnd(){seed=(seed*1664525+1013904223)>>>0;return (seed+.5)/4294967296}function normal(){return Math.sqrt(-2*Math.log(rnd()))*Math.cos(2*Math.PI*rnd())}function val(k){return Number($('#'+k).value)}
function update(){document.querySelectorAll('input[type=range]').forEach(e=>$('#'+e.id+'-v').textContent=e.value);let html='';if(id==='mean'){let a=[val('a'),val('b'),val('c')],m=avg(a),sq=sum(a.map(x=>(x-m)**2));html=chart(a.map((y,i)=>[i+1,y]),[[1,m],[3,m]])+`<div class="math">平均数 = ${fmt(m)}<br>SXX = ${fmt(sq)}<br>样本方差 = SXX / 2 = ${fmt(sq/2)}</div><p>每个数减均值：${a.map(v=>fmt(v-m)).join('，')}。这些差的和仍为 0。</p>`}
if(id==='ols'){let p=[[0,1],[1,2],[2,2],[3,4],[4,6]],a=val('a'),b=val('b'),sse=sum(p.map(([x,y])=>(y-a-b*x)**2));html=chart(p,[[0,a],[4,a+4*b]])+`<div class="math">ŷ = ${fmt(a)} + ${fmt(b)}x<br>误差平方和 RSS = ${fmt(sse)}</div><p>同一批点中，RSS 越小越贴近。最小二乘解为 a=0.6，b=1.2，RSS=1.6。拟合好不等于因果关系。</p>`}
if(id==='sampling'){let n=val('n'),s=val('sigma'),means=Array.from({length:100},()=>5+s*sum(Array.from({length:n},normal))/n),m=avg(means),sd=Math.sqrt(sum(means.map(x=>(x-m)**2))/99);html=chart(means.map((y,i)=>[i+1,y]),[[1,5],[100,5]])+`<div class="math">理论 SE = σ/√n = ${fmt(s/Math.sqrt(n))}<br>这 100 次均值的样本标准差 = ${fmt(sd)}</div><p>一个点表示一次抽样得到的均值，不是原始观测。模拟结果会波动，不必恰好等于理论值。总体均值始终是 5。</p>`}
if(id==='matrix'){let x=val('x'),a=val('a'),b=val('b');html=`<h2>行 × 列 → 一个数</h2><div class="math">[ 1　${x} ] × [ ${a}　${b} ]ᵀ<br>= 1×${a} + ${x}×${b}<br>= ${a+x*b}</div><p>维度：(1×2) × (2×1) = (1×1)。前面的 1 是截距列。</p><p>换成 n 个样本，就是 Xβ；每一行重复同样的乘加。</p>`}
if(id==='test'){let b=val('b'),se=val('se'),t=b/se,c=2.100922;html=`<div class="math">t = (${fmt(b)} − 0) / ${fmt(se)} = ${fmt(t)}<br>95% CI = [${fmt(b-c*se)}, ${fmt(b+c*se)}]</div><p class="notice">${Math.abs(t)>c?'|t| 大于临界值，拒绝 H₀；区间不含 0。':'|t| 不超过临界值，不拒绝 H₀；区间包含 0。'}</p><p>不拒绝不代表证明 β=0。这里使用正态误差线性模型的 t 推断条件；没有显示未经计算的 p 值。</p>`}
if(id==='prediction'){let x=val('x'),mu=3+x,h=1/25+x*x/50,c=2.0686576*2,ci=c*Math.sqrt(h),pi=c*Math.sqrt(1+h);html=`<div class="math">预测中心 = ${fmt(mu)}<br>均值 CI：[${fmt(mu-ci)}, ${fmt(mu+ci)}]<br>个体 PI：[${fmt(mu-pi)}, ${fmt(mu+pi)}]</div><div class="bar-row">均值半宽 <progress value="${ci}" max="6"></progress> ${fmt(ci)}</div><div class="bar-row">个体半宽 <progress value="${pi}" max="6"></progress> ${fmt(pi)}</div><p>位置越远离 x̄，杠杆 h 越大。个体预测还要加一个新误差，因此更宽。这里只演示固定模型下的公式，不保证外推合理。</p>`}
if(id==='collinear'){let e=val('eps'),d=val('perturb'),x=[-2,-1,0,1,2],z=[1,-2,2,-2,1],u=x.map((v,i)=>v+e*z[i]),y=x.map((v,i)=>1+2*v+(i===0?d:0)),my=avg(y),xx=sum(x.map(v=>v*v)),uu=sum(u.map(v=>v*v)),xu=sum(x.map((v,i)=>v*u[i])),det=xx*uu-xu*xu;if(det<1e-10)html='<div class="notice warn">ε=0：两列完全相同。OLS 仍有最小值，但两个斜率无法唯一拆开，VIF 发散。</div>';else{let xy=sum(x.map((v,i)=>v*(y[i]-my))),uy=sum(u.map((v,i)=>v*(y[i]-my))),b1=(xy*uu-uy*xu)/det,b2=(uy*xx-xy*xu)/det;html=`<div class="math">b₁ = ${fmt(b1)}<br>b₂ = ${fmt(b2)}<br>b₁+b₂ = ${fmt(b1+b2)}<br>VIF = ${fmt(1/(1-xu*xu/xx/uu))}</div><p>ε=${e}，扰动=${d}。高度相关时，单个系数容易大幅变化，组合预测却可能仍相近。</p>`}}
if(id==='overfit'){let degree=val('degree'),xs=Array.from({length:12},(_,i)=>-1+2*i/11),ys=xs.map((x,i)=>Math.sin(2.6*x)+.25*Math.sin(i*7+1)),test=Array.from({length:40},(_,i)=>{let x=-.98+1.96*i/39;return [x,Math.sin(2.6*x)+.25*Math.cos(i*5+2)]}),design=xs.map(x=>Array.from({length:degree+1},(_,k)=>x**k)),a=Array.from({length:degree+1},(_,j)=>Array.from({length:degree+1},(_,k)=>sum(design.map(r=>r[j]*r[k])))),b=Array.from({length:degree+1},(_,j)=>sum(design.map((r,i)=>r[j]*ys[i]))),coef=solve(a,b),pred=x=>sum(coef.map((b,j)=>b*x**j)),train=avg(xs.map((x,i)=>(pred(x)-ys[i])**2)),testM=avg(test.map(([x,y])=>(pred(x)-y)**2));html=chart(xs.map((x,i)=>[x,ys[i]]),Array.from({length:101},(_,i)=>{let x=-1+i/50;return[x,pred(x)]}),test)+`<div class="math">训练 MSE = ${fmt(train)}<br>留出 MSE = ${fmt(testM)}</div><p>蓝黑点是训练数据，橙点是留出数据，蓝线是拟合曲线。不能用训练误差代替泛化表现；反复看留出结果调参，也会让留出集不再独立。</p>`}
if(id==='code'){let lines=[['x <- c(1, 2, 3)','建立数值向量 x：1, 2, 3'],['y <- c(2, 4, 5)','建立响应向量 y：2, 4, 5'],['d <- data.frame(x, y)','得到 3 行、2 列的数据框'],['fit <- lm(y ~ x, data = d)','拟合 y 对 x 的含截距最小二乘回归'],['coef(fit)','(Intercept) = 0.6667；x = 1.5'],['predict(fit, data.frame(x = 4))','输出 6.6667。这是外推，解释要谨慎。']];html=`<h2>输入 → 运算 → 输出</h2>${lines.map(([c,t],i)=>`<div class="trace-line"><pre><code>${esc(c)}</code></pre><p class="trace-explain">${i<line?t:'先猜这一行做什么，再执行下一行。'}</p></div>`).join('')}<p class="small muted">已追踪 ${line}/6 行。演示数据已校验，不能执行你自己的 R 代码。</p>`;$('#nextline').disabled=line>=6}
$('#labresult').innerHTML=html}
document.querySelectorAll('input[type=range]').forEach(e=>e.oninput=update);$('#labnote').oninput=e=>{S.notes['lab-'+id]=e.target.value;save()};if($('#best'))$('#best').onclick=()=>{$('#a').value=.6;$('#b').value=1.2;update()};if($('#resample'))$('#resample').onclick=update;if($('#nextline'))$('#nextline').onclick=()=>{line++;update()};if($('#resetcode'))$('#resetcode').onclick=()=>{line=0;update()};update()}
function advancedLab(id){const titles={shrink:'正则化：同一信号怎样被收缩',pcaview:'PCA：转动投影方向',threshold:'分类阈值：漏报与误报',attention:'注意力：得分变成权重',rankview:'低秩更新：参数预算'};let controls='',intro='',unit='ridge';if(id==='shrink'){controls=slider('z','未收缩信号 z',-5,5,3,.1)+slider('lam','惩罚强度 λ',0,5,1,.1);intro='先预测：λ 增大时，哪个估计会直接变成 0？';unit='lasso'}if(id==='pcaview'){controls=slider('angle','投影方向角度（度）',-90,90,0,1)+'<button class="btn secondary" id="pca-best">找到最大方差方向</button>';intro='固定中心化点云。旋转蓝线，比较投影方差与丢失的信息。';unit='pca'}if(id==='threshold'){controls=slider('cut','判正阈值',0,1,.5,.05);intro='固定 10 个概率与真实标签。阈值下降时，会找回更多正类，还是产生更多误报？';unit='classmetrics'}if(id==='attention'){controls=slider('score1','第一项匹配得分',-4,4,0,.1)+slider('score2','第二项匹配得分',-4,4,1,.1);intro='两项 value 固定为 2 和 6。拖动匹配得分，看 softmax 怎样改变加权输出。';unit='transformer'}if(id==='rankview'){controls=slider('rank','更新 rank',1,64,4,1);intro='一个 64×64 原权重矩阵保持冻结。改变 LoRA 中间维数，核对 BA 的形状与参数。';unit='lora'}
shell(heading(titles[id],intro)+`<div class="pill-row">${Object.entries(labsList).map(([k,v])=>`<a class="pill ${k===id?'active':''}" href="#labs/${k}">${v}</a>`).join('')}</div><div class="grid grid-main section-space"><section class="card"><div id="labresult" aria-live="polite"></div></section><aside class="card"><h2>先预测，再拖动</h2>${controls}<label class="field">我的观察<textarea id="adv-note">${esc(S.notes['lab-'+id]||'')}</textarea></label>${link(unit,'回到讲解与练习')}</aside></div>`,'labs');let val=k=>Number($('#'+k).value);const raw=[[-3,-2],[-2,-.6],[-.5,-1],[1,.8],[2,1.6],[3,1.2]],mx=avg(raw.map(p=>p[0])),my=avg(raw.map(p=>p[1])),pts=raw.map(([x,y])=>[x-mx,y-my]);function draw(){document.querySelectorAll('input[type=range]').forEach(e=>$('#'+e.id+'-v').textContent=e.value);let h='';if(id==='shrink'){let z=val('z'),l=val('lam'),r=z/(1+l),a=Math.sign(z)*Math.max(Math.abs(z)-l,0);h=`<h2>三个估计并排看</h2><div class="math">未惩罚：${fmt(z)}<br>Ridge：${fmt(r)}<br>Lasso：${fmt(a)}</div><p>本实验的一维目标分别为：½(z−b)²，½(z−b)²+λb²/2，½(z−b)²+λ|b|。</p><p>这里的 Ridge 解是 z/(1+λ)，Lasso 解是软阈值。多维相关设计下不能直接把这个软阈值逐个套在 OLS 系数上。</p>`}if(id==='pcaview'){let t=val('angle')*Math.PI/180,c=Math.cos(t),s=Math.sin(t),pro=pts.map(([x,y])=>x*c+y*s),variance=sum(pro.map(x=>x*x))/(pts.length-1),total=sum(pts.map(([x,y])=>x*x+y*y))/(pts.length-1);h=chart(pts,[[-4*c,-4*s],[4*c,4*s]])+`<div class="math">投影样本方差 = ${fmt(variance)}<br>保留比例 = ${fmt(variance/total*100)}%<br>正交重建平方误差 = ${fmt((total-variance)*(pts.length-1))}</div><p>最大化保留方差等价于在一维正交投影中最小化重建平方误差。此图按数据范围绘制，横纵轴尺度未必相同；方向角度按原数据坐标计算。</p>`}if(id==='threshold'){let p=[.05,.12,.2,.32,.42,.55,.65,.75,.85,.95],y=[0,0,1,0,1,0,1,1,0,1],c=val('cut'),tp=0,fp=0,tn=0,fn=0;p.forEach((a,i)=>{if(a>=c)y[i]?tp++:fp++;else y[i]?fn++:tn++});h=`<h2>混淆矩阵</h2><div class="grid grid-2"><p>TP 真阳性：${tp}</p><p>FP 误报：${fp}</p><p>FN 漏报：${fn}</p><p>TN 真阴性：${tn}</p></div><div class="math">Precision = ${tp+fp?fmt(tp/(tp+fp)):'未定义（没有判正）'}<br>Recall = ${fmt(tp/(tp+fn))}<br>Accuracy = ${fmt((tp+tn)/10)}</div><p>概率：${p.join('，')}<br>真值：${y.join('，')}</p><p>先说清哪种错误代价高，再用验证集选阈值。不要反复在最终测试集上调整。</p>`}if(id==='attention'){let a=val('score1'),b=val('score2'),m=Math.max(a,b),ea=Math.exp(a-m),eb=Math.exp(b-m),w=ea/(ea+eb);h=`<div class="math">第一项权重 = ${fmt(w)}<br>第二项权重 = ${fmt(1-w)}<br>输出 = 2×${fmt(w)} + 6×${fmt(1-w)}<br>= ${fmt(2*w+6*(1-w))}</div><p>两个匹配得分相同时，权重各为 1/2。给两项得分同时加同一个常数，不改变权重。</p><p>这里只拆解一个查询的加权汇总，并非完整 Transformer 训练。权重不自动等同于因果重要性。</p>`}if(id==='rankview'){let r=val('rank'),count=128*r;h=`<div class="math">B：64×${r}；A：${r}×64<br>BA：64×64<br>可训练因子参数 = ${count}<br>完整矩阵参数 = 4096<br>因子 / 完整 = ${fmt(count/4096*100)}%</div><p>当 r 较大时，因子参数甚至不再节省。低秩更新有用的前提是所需变化能用较小 r 表达。</p><p>冻结主干仍要保存和计算；参数比例不是实际显存或推理速度比例。</p>`}$('#labresult').innerHTML=h}
document.querySelectorAll('input[type=range]').forEach(e=>e.oninput=draw);$('#adv-note').oninput=e=>{S.notes['lab-'+id]=e.target.value;save()};if($('#pca-best'))$('#pca-best').onclick=()=>{let xx=sum(pts.map(p=>p[0]**2)),yy=sum(pts.map(p=>p[1]**2)),xy=sum(pts.map(p=>p[0]*p[1]));$('#angle').value=Math.atan2(2*xy,xx-yy)/2*180/Math.PI;draw()};draw()}

function examQuestions(v){const b=v==='B';let rows=b?[
['连续价格预测属于？',['回归','分类','聚类'],0,'mltask','目标是连续数值，属于回归。'],
['全数据标准化后再做 CV，有何风险？',['没有风险','信息泄漏','样本变少'],1,'dataprep','预处理应在训练折内拟合。'],
['PCA 主要优化什么？',['最大类别间隔','保留方差/减少正交重建误差','预测标签准确率'],1,'pca','PCA 不用标签，围绕输入变化方向。'],
['k-means 的 K 指？',['特征数','簇数','样本数'],1,'kmeans','K 是选定的簇数量。'],
['DBSCAN 的噪声标签能直接证明数据错误吗？',['能','不能'],1,'clusterother','这是算法在当前密度参数下的分类。'],
['神经网络无非线性激活，多层线性组合仍是？',['线性/仿射映射','任意非线性','必然概率'],0,'neuron','线性/仿射变换复合仍是同类映射。'],
['反向传播主要做什么？',['计算梯度','划分测试集','创造标签'],0,'backprop','沿计算图利用链式法则求导。'],
['LoRA 低秩约束作用于？',['原权重必须低秩','权重更新','所有输入'],1,'lora','低秩约束施加于更新 BA。'],
['生成结果逼真是否保证事实真实？',['保证','不保证'],1,'generative','视觉或语言逼真不等于事实正确。'],
['最可靠的最终测试做法？',['重复选测试最好结果','保留独立数据到最终评估','先用测试标签选变量'],1,'generalization','最终测试不参与模型选择。'],
['聚类点 0、2、4 的更新中心是多少？',null,2,'kmeans','中心为均值 6/3=2。'],
['奇异值为 5、2、1，秩 2 近似平方重建误差？',null,1,'lowrank','丢掉的奇异值平方和为 1。'],
['协方差特征值为 8、2，首主成分解释比例？',null,.8,'pca','8/(8+2)=0.8。'],
['ReLU(−3) 是多少？',null,0,'neuron','max(0,−3)=0。'],
['w=2、梯度=−3、学习率=.1，一步更新后 w？',null,2.3,'gradient','2−0.1×(−3)=2.3。'],
['n=240、batch=60，2 个 epoch 共更新几次？',null,8,'training','每轮 4 次，共 8 次。'],
['注意力权重 .25、.75，对应 value 为 2、6，输出？',null,5,'transformer','.25×2+.75×6=5。'],
['64×64 权重、LoRA rank=2，因子参数数？',null,256,'lora','2×(64+64)=256。'],
['训练误差 .1、测试误差 .3，观察差距？',null,.2,'generalization','.3−.1=.2。'],
['100 个负例中 FP=20，FPR 是多少？',null,.2,'roc','20/100=.2。']
]:[
['预测是否流失属于？',['回归','分类','聚类'],1,'mltask','标签是离散类别。'],
['哪个集合用于最后评估，不应反复调参？',['训练集','测试集','所有集合都随意'],1,'mlflow','测试集用于最终评估。'],
['缺失数据能无条件填 0 吗？',['能','不能'],1,'dataprep','零可能具有真实含义。'],
['Python 列表首元素下标？',['0','1','−2'],0,'pylist','Python 下标从 0 开始。'],
['强正则化的常见影响？',['方差可能减小，偏差可能增加','所有误差为零','必然因果正确'],0,'biasvariance','收缩常以偏差换稳定。'],
['kNN 很小的 k 常见风险？',['过度平滑','受局部噪声影响','不再需要距离'],1,'knn','小 k 容易追逐局部样本。'],
['树无限加深通常要担心？',['过拟合','无法表示非线性','必然速度更快'],0,'tree','深树可能记住噪声。'],
['Boosting 与 Bagging 一样只是并行平均吗？',['是','不是'],1,'boosting','Boosting 是逐轮修正损失。'],
['准确率 99%，正类仅 1%，就足够说明有效吗？',['是','否'],1,'classmetrics','全预测负类也可能达到该准确率。'],
['特征重要性很高就证明因果吗？',['证明','不证明'],1,'responsible','模型关联不等于因果识别。'],
['标准化训练均值 4、标准差 2，新观测 8，结果？',null,2,'dataprep','(8−4)/2=2。'],
['真实值 2、4，预测 1、6，MSE？',null,2.5,'casework','(1²+2²)/2=2.5。'],
['回归 ŷ=1+3x，在 x=2 的预测？',null,7,'ols','1+3×2=7。'],
['一维 ½(z−b)²+λ|b|，z=3、λ=1，Lasso 解？',null,2,'lasso','软阈值 3−1=2。'],
['三个回归近邻的值 2、5、8，均值预测？',null,5,'knn','15/3=5。'],
['正负各半的分类节点 Gini？',null,.5,'tree','1−.5²−.5²=.5。'],
['旧预测 2、新树 3、步长 .1，提升后预测？',null,2.3,'boosting','2+.1×3=2.3。'],
['TP=12、FP=3，Precision？',null,.8,'classmetrics','12/(12+3)=.8。'],
['TP=12、FN=8，Recall？',null,.6,'classmetrics','12/(12+8)=.6。'],
['FP=5、TN=45，FPR？',null,.1,'roc','5/(5+45)=.1。']
];return rows.map(([prompt,options,answer,unit,explain],i)=>({id:'e'+(i+1),prompt,options,answer,unit,explain,points:5,tolerance:.005}))}
function score(e){return examQuestions(e.version).map(q=>{let v=e.answers[q.id],n=numeric(v??'');return {...q,value:v,ok:q.options?v!==undefined&&String(v)===String(q.answer):Number.isFinite(n)&&Math.abs(n-q.answer)<=q.tolerance}})}
function exam(){if(S.exam&&!S.exam.submitted){examRun();return}let e=S.exam;shell(heading('机器学习模拟测验','自编题 · 每卷 20 题 / 100 分 · 45 分钟 · 小计算与应用判断')+`<section class="card"><h2>先选适合的阶段</h2><p>A 卷覆盖第 1—7 章的基础、数据、回归、分类、树与评价。B 卷为全课程综合，更侧重降维、神经网络与现代方法。它们不是学校官方考卷。</p><p>计算题支持小数与分数，误差容许为 0.005。开始后计时持续，刷新可续答；到时自动交卷。</p><div class="actions"><button class="btn" id="exam-a">A 卷 · 基础阶段</button><button class="btn secondary" id="exam-b">B 卷 · 综合阶段</button><a href="#coursecheck">先做章节查漏</a></div></section>${e?.submitted?examReport(e):''}<section class="card section-space"><h2>历史测验</h2>${S.history.length?S.history.map(h=>`<p>${new Date(h.time).toLocaleString('zh-CN')} · ${h.version} 卷 · ${h.score}/100</p>`).join(''):'<p>还没有测验记录。先完成基础单元也完全可以。</p>'}</section>`,'exam');for(let v of ['a','b'])$('#exam-'+v).onclick=()=>{S.exam={version:v.toUpperCase(),start:Date.now(),end:Date.now()+2700000,answers:{},proof:'',submitted:false};save();examRun()}}
function examRun(){let e=S.exam;shell(heading(e.version+' 卷 · 先独立完成','每题 5 分；可以留空稍后返回。输入自动保存在当前浏览器。')+`<div class="exam-header"><strong>剩余 <span id="timer"></span></strong><span>满分 100</span></div><form id="exam-form" class="card">${examQuestions(e.version).map((q,i)=>`<fieldset class="question"><legend>${i+1}. ${q.prompt}</legend>${q.options?q.options.map((t,k)=>`<label class="option"><input type="radio" name="${q.id}" value="${k}" ${String(e.answers[q.id])===String(k)?'checked':''}> ${t}</label>`).join(''):`<label class="field">计算结果<input name="${q.id}" inputmode="decimal" value="${esc(e.answers[q.id]||'')}" placeholder="可填分数或小数"></label>`}</fieldset>`).join('')}<button class="btn">交卷并查看解析</button></form>`,'exam');$('#exam-form').oninput=ev=>{if(ev.target.name)e.answers[ev.target.name]=ev.target.value;save()};$('#exam-form').onsubmit=ev=>{ev.preventDefault();submitExam()};tick()}
function submitExam(){let e=S.exam;if(!e||e.submitted)return;e.submitted=true;e.submittedAt=Date.now();e.score=sum(score(e).filter(q=>q.ok).map(q=>q.points));S.history.unshift({time:e.submittedAt,version:e.version,score:e.score});S.history=S.history.slice(0,30);save();if(location.hash==='#exam')exam();else toast('测验时间已到，已自动交卷。')}
function tick(){let e=S.exam;if(!e||e.submitted)return;let n=Math.max(0,Math.ceil((e.end-Date.now())/1000));if($('#timer'))$('#timer').textContent=Math.floor(n/60)+':'+String(n%60).padStart(2,'0');if(!n)submitExam()}
function examReport(e){let qs=score(e),weak=[...new Set(qs.filter(q=>!q.ok).map(q=>q.unit))];return `<section class="card section-space"><h2>${e.version} 卷结果：${e.score}/100</h2><p>分数只表示这组题的表现，不等于完整掌握。优先复习下面的知识点。</p><div class="actions">${weak.length?weak.map(id=>link(id)).join(''):'本卷全对，试着隔天再用新例子解释原理。'}</div>${qs.map(q=>`<details><summary>${q.ok?'✓':'需复习'} · ${q.prompt}</summary><p>你的答案：${q.value===undefined||q.value===''?'未作答':esc(q.options?q.options[Number(q.value)]:q.value)}</p><p>参考：${q.options?q.options[q.answer]:fmt(q.answer)}。${q.explain}</p></details>`).join('')}</section>`}
function mlLab(id){let titles={neighbors:'最近邻：距离、k 和预测',clusters:'聚类：中心如何改变分组',splitter:'决策树：寻找有用的切分'};let control=id==='neighbors'?slider('target','新点位置',0,10,5,.1)+slider('k','邻居数 k',1,5,3):id==='clusters'?slider('c1','左中心',0,10,1,.1)+slider('c2','右中心',0,10,9,.1):slider('cut','切分阈值',.5,5.5,2.5,.1);shell(heading(titles[id],'先预测结果，再改变一个量。小数据例子只解释机制，不代表已训练一个完整系统。')+`<div class="pill-row">${Object.entries(labsList).map(([k,v])=>`<a class="pill" href="#labs/${k}">${v}</a>`).join('')}</div><div class="grid grid-main section-space"><section class="card" id="ml-lab-result" aria-live="polite"></section><aside class="card">${control}${link(id==='neighbors'?'knn':id==='clusters'?'kmeans':'tree','回到原理与练习')}</aside></div>`,'labs');function draw(){document.querySelectorAll('input[type=range]').forEach(e=>$('#'+e.id+'-v').textContent=e.value);let h='';if(id==='neighbors'){let x=Number($('#target').value),k=Number($('#k').value),a=[[0,1],[2,2],[4,4],[7,8],[10,9]],near=[...a].sort((a,b)=>Math.abs(a[0]-x)-Math.abs(b[0]-x)||a[0]-b[0]).slice(0,k),pred=avg(near.map(p=>p[1]));h=chart(a,[[x,pred]])+`<div class="math">邻居 x：${near.map(p=>p[0]).join('、')}<br>回归预测 = ${fmt(pred)}</div><p>这里按一维距离选邻居，距离并列时选较小 x。k 变大通常更平滑，但不一定更准确。</p>`}if(id==='clusters'){let a=[0,2,3,8,9,10],c1=Number($('#c1').value),c2=Number($('#c2').value),g1=a.filter(x=>Math.abs(x-c1)<=Math.abs(x-c2)),g2=a.filter(x=>Math.abs(x-c1)>Math.abs(x-c2)),loss=sum(a.map(x=>Math.min((x-c1)**2,(x-c2)**2)));h=`<h2>按最近中心分配</h2><p>点：${a.join('、')}</p><div class="math">第一组：${g1.join('、')||'空'}<br>第二组：${g2.join('、')||'空'}<br>当前平方距离总和 = ${fmt(loss)}</div><p>下一次均值更新的中心为 ${g1.length?fmt(avg(g1)):'空组需重新初始化'} 和 ${g2.length?fmt(avg(g2)):'空组需重新初始化'}。你可把滑块移到这两个均值，观察下一轮。</p>`}if(id==='splitter'){let t=Number($('#cut').value),x=[0,1,2,3,4,5,6],y=[0,0,1,0,1,1,1],left=y.filter((_,i)=>x[i]<=t),right=y.filter((_,i)=>x[i]>t),g=a=>{let p=avg(a);return 1-p*p-(1-p)**2},cost=(left.length*g(left)+right.length*g(right))/7;h=`<h2>一个阈值把样本分为两组</h2><p>x：${x.join('、')}<br>类别：${y.join('、')}</p><div class="math">左组标签：${left.join('、')}<br>右组标签：${right.join('、')}<br>加权 Gini = ${fmt(cost)}</div><p>比较不同切分的加权不纯度，而不是只看某一组。实际树还要考虑最小叶子样本数与深度。</p>`}$('#ml-lab-result').innerHTML=h}document.querySelectorAll('input[type=range]').forEach(e=>e.oninput=draw);draw()}

function projects(){const items=[
['回归：先打败一个简单基线','先学均值、回归线、训练与测试划分。','用 90 个合成样本拟合面积与价格关系，在另 30 个样本上比较误差。','训练均值预测的测试 MSE 约 2437.00；线性回归约 109.92。价格单位为自定义单位，MSE 单位为其平方。','把噪声标准差 12 改成 24，先预测误差怎样变，再运行。不要根据测试结果反复选模型。','ols'],
['分类决策：漏判和误报如何取舍','先学混淆矩阵、精确率、召回率。','给定 10 个演示概率与真实标签，比较阈值 0.2、0.5、0.8；每次漏判代价设为 5，误报为 1。','对应总代价是 3、12、21。低阈值在这个玩具例子中漏判更少；这不是所有任务的最优阈值。','将漏判代价改为 1，再比较选择。这里的概率是人为指定的，项目不包含分类器训练。','classmetrics'],
['聚类：亲手完成分配与更新','先学均值、距离、k-means。','把 0、2、3、8、9、10 分成两组：先按最近中心分配，再算每组均值，重复到稳定。','初始中心 0、10 时收敛到约 1.6667、9；组内平方和约 6.6667。','修改初始中心并记录过程。思考换一组数据是否可能得到不同局部结果。','kmeans']];shell(heading('三个最小项目','每个项目分两天：第一天预测和手算；第二天运行、修改与解释。')+`<section class="card soft"><h2>手机先理解，电脑再运行</h2><p>脚本只用 Python 标准库。完成 Python 前 3 节后，下载文件并运行。代码中的每个项目都有注释；先一次读一段。</p><div class="actions"><a href="三个最小项目.py" download>下载项目脚本</a><a href="三个最小项目.ipynb" download>下载 Notebook</a><a href="合成回归数据.csv" download>下载合成数据</a><a href="#rstart">补 Python 基础</a></div><p class="small muted">网页不执行任意代码。示例数据与结果用于学习，不代表真实业务结论。</p></section>${items.map(([title,pre,task,out,change,id],i)=>`<section class="card section-space"><h2>${i+1}. ${title}</h2><p><strong>先修：</strong>${pre}</p><p><strong>任务：</strong>${task}</p><details><summary>先预测，再核对示例结果</summary><p>${out}</p></details><p><strong>改一次：</strong>${change}</p>${link(id,'回到对应知识点')}<label class="field">实验记录<textarea data-project="${i}" rows="5" placeholder="我的预测 → 实际结果 → 原因 → 不能得出的结论">${esc(S.notes['project-'+i]||'')}</textarea></label></section>`).join('')}`,'path');document.querySelectorAll('[data-project]').forEach(e=>e.oninput=()=>{S.notes['project-'+e.dataset.project]=e.value;save()})}

function render(){const [r='today',id,tab]=location.hash.slice(1).split('/');if(r==='learn')learn(id,tab);else if(r==='path')path();else if(r==='projects')projects();else if(r==='rstart')rStart();else if(r==='rtrace')rTrace(id);else if(r==='diagnostic')diagnostic();else if(r==='labs')labs(id);else if(r==='review')review();else if(r==='exam')exam();else if(r==='resources')resources(id);else if(r==='chapter')chapter(id);else if(r==='foundations')foundations();else if(r==='chaptercheck')chapterCheck(id);else if(r==='coursecheck')courseCheck();else today();window.scrollTo(0,0)}
window.addEventListener('hashchange',render);setInterval(tick,1000);render();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'get_learning_progress',description:'读取本机学习进度，不修改学习记录',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true},execute:async()=>({content:[{type:'text',text:JSON.stringify({lessons:C.lessons.map(l=>({id:l.id,title:l.title,status:status(l)})),due:due().length,next:next().id})}]})});document.modelContext.registerTool({name:'open_lesson',description:'打开指定学习单元，不替学习者答题',inputSchema:{type:'object',properties:{id:{type:'string',enum:C.lessons.map(l=>l.id)}},required:['id']},execute:async({id})=>{if(!lesson(id))throw Error('未知课程');location.hash='learn/'+id;return {content:[{type:'text',text:'已打开 '+lesson(id).title}]}}})}catch(err){console.warn('WebMCP 注册不可用',err)}}
})();
